### ISSUE TITLE
Close lazygit using cmd+w or toggle command

### ISSUE THREAD

**Issue by ducan-ne** [tom-pollak/lazygit-vscode#3]
I know we can use "q" to quit lazygit but Is it possible to close lazygit tab using cmd+w like we're closing a file? It feels nature than the "q" command, or maybe at least use toggle command to toggle the visiblity of the lazygit tab

Why: I can't use the shortcut navigating around files/tabs inside lazygit tab (alt+cmd+right brokes), and only want lazygit when needed

**Comment by tom-pollak** [comment]
can you provide an example? It should be able to be toggled with cmd+shift+l and closed the same way as other tabs (cmd+w)

https://github.com/user-attachments/assets/34ad592f-e05c-406c-bd0b-e2da0cddfbeb

**Comment by tom-pollak** [comment]
is it possible that your on windows, and ctrl commands are captured by the shell?

```json
  "terminal.integrated.sendKeybindingsToShell": true, // if this is set
  "terminal.integrated.commandsToSkipShell": ["lazygit-vscode.toggle", "workbench.action.closeWindow"], // then you might need this (on windows)
```

lmk if this fixes it for you, I don't have a windows pc to test on

**Comment by ducan-ne** [comment]
@tom-pollak I'm run it on mac though, same device as you, but not sure if it's because I'm using Cursor not Vscode

> is it possible that your on windows, and ctrl commands are captured by the shell?

https://github.com/user-attachments/assets/1387531e-11c0-4eb6-9445-e7edd1a6186f
https://github.com/user-attachments/assets/4701bb33-7a39-446e-8ae3-823fcbc0f02b

just tried but it seems like it doesn't work for me, the opt+cmd+right even open the terminal 🥲

and 
>  cmd+shift+l and closed the same way as other tabs
my bad, I didn't mean it doesn't work but it only toggles visiblity of its tab, not closing the tab (checkout the video), not sure on your side because you just hide the tabs bar.

**Comment by tom-pollak** [comment]
> toggles visiblity of its tab, not closing the tab, not sure on your side because you just hide the tabs bar.

Yeah this is intended behaviour -- it's just because my tabs are hidden. Functionally equal to closing the window? It should focus the most recent active tab on toggle. Feel free to add a pr to close the window on toggle if you like.

Cmd+w is more strange, can you enable keyboard troubleshooting and try again?

https://code.visualstudio.com/docs/getstarted/keybindings#_troubleshooting-keybindings

**Comment by ducan-ne** [comment]
@tom-pollak sorry it seems like because I have cmd+w a shortcut to close terminal and this tab actually a terminal, will try to replace it to another shortcut, I will close this issue
