### ISSUE TITLE
Fullscreen 

### ISSUE THREAD

**Issue by rodrigore** [tom-pollak/lazygit-vscode#4]
Hey @tom-pollak thank you for this extension. I'm testing vscode and I'm trying your extension and is working really good inside neovim.

I was wondering if is possible to toggle Lazygit in full screen, even if I have a vertical split or too many splits?

Right now if I have for example a vertical split, Lazygit appear in the current Editor: 
<img width="2790" alt="image" src="https://github.com/user-attachments/assets/172e916f-403c-41f4-8926-b23756f127ed">

Thanks!

**Comment by tom-pollak** [comment]
(vscode-neovim ftw!) I don't usually use splits much, that's a great idea 😄 pushed change in v0.1.6 [ed49d94](https://github.com/tom-pollak/lazygit-vscode/commit/ed49d9456e416d2d4a5419ae58893e6c9fece67d)

**Comment by tom-pollak** [comment]
@rodrigore thanks for flagging, super easy fix 🙂 lmk if there's any other issues, change should be pushed in 0.1.8

**Comment by tom-pollak** [comment]
yeah I can use `workbench.action.toggleMaximizeEditorGroup` instead of `workbench.action.evenEditorWidths` which would solve this.

I'll leave the issue open for now, because it also doesn't untoggle perfectly if you change window (e.g. through `e` or selecting another tab). I'll finish it up soon
