### ISSUE TITLE
Does not handle workspace with multiple repos

### ISSUE THREAD

**Issue by pcseanmckay** [tom-pollak/lazygit-vscode#6]
When using this extension in a workspace that has multiple repos, the extension only ever opens lazygit using the first repo.

There should be a way to determine the current repo in the workspace to use based on the active editor tab that has the current focus when the extension is activated.

**Comment by tom-pollak** [comment]
I'll have a look at this. In the meantime, have you tried:

1. Use <C-r> to switch between recent repos in lazygit.
2. Toggling the lazygit window keeps your session, so your last repo you accessed stays accessible.

Does this cover your workflow? lmk

**Comment by pcseanmckay** [comment]
Yes, that does for now :)

**Comment by pcseanmckay** [comment]
The only issue I have now is that for a repo I haven't opened in lazygit previously, I have to close out your instance, run lazygit manually inside the repo, then re-open your lazygit for it to show up.
